In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\Easwar\AppData\Roaming\Python\Python311\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Easwar\AppData\Roaming\Python\Python311\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Easwar\AppData\Roaming\Python\Python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Easwar\AppData\Roaming\Python\Python311\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\Easwar\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [14]:
import pandas as pd
data=pd.read_csv("classificationloan.csv")
data

,Loan ID,No. of Dependencies,Education,Self Employed,Income/Annum (?),Loan Amount (?),Loan Term (Months),Credit Score,residental_status,commercial_assets,luxury_assets,bank_assets,Loan Status
0,L001,0,Graduate,No,"8,50,000","15,00,000",120,810,"25,00,000",0,"3,00,000","6,00,000",Approved
1,L002,2,Graduate,Yes,"6,20,000","18,00,000",180,760,"18,00,000","5,00,000","2,00,000","4,00,000",Approved
2,L003,3,Not Graduate,No,"2,80,000","12,00,000",240,590,"8,00,000",0,"50,000","1,20,000",Rejected
3,L004,1,Graduate,No,"12,00,000","20,00,000",180,845,"40,00,000","10,00,000","8,00,000","12,00,000",Approved
4,L005,4,Not Graduate,Yes,"3,50,000","15,00,000",240,610,"10,00,000","1,00,000","1,00,000","2,50,000",Rejected
5,L006,0,Graduate,No,"15,00,000","25,00,000",120,890,"50,00,000","20,00,000","15,00,000","20,00,000",Approved
6,L007,2,Graduate,No,"5,00,000","10,00,000",60,720,"16,00,000",0,"1,50,000","3,00,000",Approved
7,L008,5,Not Graduate,Yes,"2,20,000","14,00,000",300,540,"6,00,000",0,0,"80,000",Rejected
8,L009,1,Graduate,Yes,"9,00,000","16,00,000",120,790,"28,00,000","8,00,000","4,00,000","7,00,000",Approved
9,L010,3,Not Graduate,No,"3,80,000","13,00,000",180,630,"12,00,000","2,00,000","1,20,000","2,20,000",Rejected

In [8]:
data.shape

(10, 13)

In [15]:
data.nunique()

Loan ID                10
No. of Dependencies     6
Education               2
Self Employed           2
Income/Annum (?)       10
Loan Amount (?)         9
Loan Term (Months)      5
Credit Score           10
residental_status      10
commercial_assets       7
luxury_assets          10
bank_assets            10
Loan Status             2
dtype: int64

In [3]:
data.duplicated().sum()

np.int64(0)

In [16]:
data_new= data.drop_duplicates(keep='first').reset_index(drop=True)
data_new

,Loan ID,No. of Dependencies,Education,Self Employed,Income/Annum (?),Loan Amount (?),Loan Term (Months),Credit Score,residental_status,commercial_assets,luxury_assets,bank_assets,Loan Status
0,L001,0,Graduate,No,"8,50,000","15,00,000",120,810,"25,00,000",0,"3,00,000","6,00,000",Approved
1,L002,2,Graduate,Yes,"6,20,000","18,00,000",180,760,"18,00,000","5,00,000","2,00,000","4,00,000",Approved
2,L003,3,Not Graduate,No,"2,80,000","12,00,000",240,590,"8,00,000",0,"50,000","1,20,000",Rejected
3,L004,1,Graduate,No,"12,00,000","20,00,000",180,845,"40,00,000","10,00,000","8,00,000","12,00,000",Approved
4,L005,4,Not Graduate,Yes,"3,50,000","15,00,000",240,610,"10,00,000","1,00,000","1,00,000","2,50,000",Rejected
5,L006,0,Graduate,No,"15,00,000","25,00,000",120,890,"50,00,000","20,00,000","15,00,000","20,00,000",Approved
6,L007,2,Graduate,No,"5,00,000","10,00,000",60,720,"16,00,000",0,"1,50,000","3,00,000",Approved
7,L008,5,Not Graduate,Yes,"2,20,000","14,00,000",300,540,"6,00,000",0,0,"80,000",Rejected
8,L009,1,Graduate,Yes,"9,00,000","16,00,000",120,790,"28,00,000","8,00,000","4,00,000","7,00,000",Approved
9,L010,3,Not Graduate,No,"3,80,000","13,00,000",180,630,"12,00,000","2,00,000","1,20,000","2,20,000",Rejected

In [5]:
data_new.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [12]:
data_new.duplicated().sum()

np.int64(0)

In [17]:
data_new

,Loan ID,No. of Dependencies,Education,Self Employed,Income/Annum (?),Loan Amount (?),Loan Term (Months),Credit Score,residental_status,commercial_assets,luxury_assets,bank_assets,Loan Status
0,L001,0,Graduate,No,"8,50,000","15,00,000",120,810,"25,00,000",0,"3,00,000","6,00,000",Approved
1,L002,2,Graduate,Yes,"6,20,000","18,00,000",180,760,"18,00,000","5,00,000","2,00,000","4,00,000",Approved
2,L003,3,Not Graduate,No,"2,80,000","12,00,000",240,590,"8,00,000",0,"50,000","1,20,000",Rejected
3,L004,1,Graduate,No,"12,00,000","20,00,000",180,845,"40,00,000","10,00,000","8,00,000","12,00,000",Approved
4,L005,4,Not Graduate,Yes,"3,50,000","15,00,000",240,610,"10,00,000","1,00,000","1,00,000","2,50,000",Rejected
5,L006,0,Graduate,No,"15,00,000","25,00,000",120,890,"50,00,000","20,00,000","15,00,000","20,00,000",Approved
6,L007,2,Graduate,No,"5,00,000","10,00,000",60,720,"16,00,000",0,"1,50,000","3,00,000",Approved
7,L008,5,Not Graduate,Yes,"2,20,000","14,00,000",300,540,"6,00,000",0,0,"80,000",Rejected
8,L009,1,Graduate,Yes,"9,00,000","16,00,000",120,790,"28,00,000","8,00,000","4,00,000","7,00,000",Approved
9,L010,3,Not Graduate,No,"3,80,000","13,00,000",180,630,"12,00,000","2,00,000","1,20,000","2,20,000",Rejected

In [14]:
data_new.columns

Index(['Loan ID', 'No. of Dependencies', 'Education', 'Self Employed',
       'Income/Annum (?)', 'Loan Amount (?)', 'Loan Term (Months)',
       'Credit Score', 'Residential Assets (?)', 'Commercial Assets (?)',
       'Luxury Assets (?)', 'Bank Assets (?)', 'Loan Status'],
      dtype='str')

In [19]:
data_new['total_assets_value']=data_new['residental_status']+data_new['commercial_assets']+data_new['luxury_assets']+data_new['bank_assets']
data_new

,Loan ID,No. of Dependencies,Education,Self Employed,Income/Annum (?),Loan Amount (?),Loan Term (Months),Credit Score,residental_status,commercial_assets,luxury_assets,bank_assets,Loan Status,total_assets_value
0,L001,0,Graduate,No,"8,50,000","15,00,000",120,810,"25,00,000",0,"3,00,000","6,00,000",Approved,"25,00,00003,00,0006,00,000"
1,L002,2,Graduate,Yes,"6,20,000","18,00,000",180,760,"18,00,000","5,00,000","2,00,000","4,00,000",Approved,"18,00,0005,00,0002,00,0004,00,000"
2,L003,3,Not Graduate,No,"2,80,000","12,00,000",240,590,"8,00,000",0,"50,000","1,20,000",Rejected,"8,00,000050,0001,20,000"
3,L004,1,Graduate,No,"12,00,000","20,00,000",180,845,"40,00,000","10,00,000","8,00,000","12,00,000",Approved,"40,00,00010,00,0008,00,00012,00,000"
4,L005,4,Not Graduate,Yes,"3,50,000","15,00,000",240,610,"10,00,000","1,00,000","1,00,000","2,50,000",Rejected,"10,00,0001,00,0001,00,0002,50,000"
5,L006,0,Graduate,No,"15,00,000","25,00,000",120,890,"50,00,000","20,00,000","15,00,000","20,00,000",Approved,"50,00,00020,00,00015,00,00020,00,000"
6,L007,2,Graduate,No,"5,00,000","10,00,000",60,720,"16,00,000",0,"1,50,000","3,00,000",Approved,"16,00,00001,50,0003,00,000"
7,L008,5,Not Graduate,Yes,"2,20,000","14,00,000",300,540,"6,00,000",0,0,"80,000",Rejected,"6,00,0000080,000"
8,L009,1,Graduate,Yes,"9,00,000","16,00,000",120,790,"28,00,000","8,00,000","4,00,000","7,00,000",Approved,"28,00,0008,00,0004,00,0007,00,000"
9,L010,3,Not Graduate,No,"3,80,000","13,00,000",180,630,"12,00,000","2,00,000","1,20,000","2,20,000",Rejected,"12,00,0002,00,0001,20,0002,20,000"

In [20]:
new=data_new.drop(columns=['residental_status','commercial_assets','luxury_assets','bank_assets'])
new

,Loan ID,No. of Dependencies,Education,Self Employed,Income/Annum (?),Loan Amount (?),Loan Term (Months),Credit Score,Loan Status,total_assets_value
0,L001,0,Graduate,No,"8,50,000","15,00,000",120,810,Approved,"25,00,00003,00,0006,00,000"
1,L002,2,Graduate,Yes,"6,20,000","18,00,000",180,760,Approved,"18,00,0005,00,0002,00,0004,00,000"
2,L003,3,Not Graduate,No,"2,80,000","12,00,000",240,590,Rejected,"8,00,000050,0001,20,000"
3,L004,1,Graduate,No,"12,00,000","20,00,000",180,845,Approved,"40,00,00010,00,0008,00,00012,00,000"
4,L005,4,Not Graduate,Yes,"3,50,000","15,00,000",240,610,Rejected,"10,00,0001,00,0001,00,0002,50,000"
5,L006,0,Graduate,No,"15,00,000","25,00,000",120,890,Approved,"50,00,00020,00,00015,00,00020,00,000"
6,L007,2,Graduate,No,"5,00,000","10,00,000",60,720,Approved,"16,00,00001,50,0003,00,000"
7,L008,5,Not Graduate,Yes,"2,20,000","14,00,000",300,540,Rejected,"6,00,0000080,000"
8,L009,1,Graduate,Yes,"9,00,000","16,00,000",120,790,Approved,"28,00,0008,00,0004,00,0007,00,000"
9,L010,3,Not Graduate,No,"3,80,000","13,00,000",180,630,Rejected,"12,00,0002,00,0001,20,0002,20,000"

In [21]:
print(new.columns.tolist())

['Loan ID', 'No. of Dependencies', 'Education', 'Self Employed', 'Income/Annum (?)', 'Loan Amount (?)', 'Loan Term (Months)', 'Credit Score', 'Loan Status', 'total_assets_value']

In [25]:
data_new

,Loan ID,No. of Dependencies,Education,Self Employed,Income/Annum (?),Loan Amount (?),Loan Term (Months),Credit Score,Loan Status,total_assets_value
0,L001,0,Graduate,No,"8,50,000","15,00,000",120,810,Approved,"25,00,00003,00,0006,00,000"
1,L002,2,Graduate,Yes,"6,20,000","18,00,000",180,760,Approved,"18,00,0005,00,0002,00,0004,00,000"
2,L003,3,Not Graduate,No,"2,80,000","12,00,000",240,590,Rejected,"8,00,000050,0001,20,000"
3,L004,1,Graduate,No,"12,00,000","20,00,000",180,845,Approved,"40,00,00010,00,0008,00,00012,00,000"
4,L005,4,Not Graduate,Yes,"3,50,000","15,00,000",240,610,Rejected,"10,00,0001,00,0001,00,0002,50,000"
5,L006,0,Graduate,No,"15,00,000","25,00,000",120,890,Approved,"50,00,00020,00,00015,00,00020,00,000"
6,L007,2,Graduate,No,"5,00,000","10,00,000",60,720,Approved,"16,00,00001,50,0003,00,000"
7,L008,5,Not Graduate,Yes,"2,20,000","14,00,000",300,540,Rejected,"6,00,0000080,000"
8,L009,1,Graduate,Yes,"9,00,000","16,00,000",120,790,Approved,"28,00,0008,00,0004,00,0007,00,000"
9,L010,3,Not Graduate,No,"3,80,000","13,00,000",180,630,Rejected,"12,00,0002,00,0001,20,0002,20,000"

In [27]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in C:\Users\Easwar\AppData\Roaming\Python\Python311\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\Easwar\AppData\Roaming\Python\Python311\site-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\Easwar\AppData\Roaming\Python\Python311\site-packages (from scikit-learn) (1.16.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\Easwar\AppData\Roaming\Python\Python311\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\Easwar\AppData\Roaming\Python\Python311\site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\Easwar\AppData\Roaming\Python\Python311\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [30]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
new['Education']=le.fit_transform(new['Education'])

In [31]:
new

,Loan ID,No. of Dependencies,Education,Self Employed,Income/Annum (?),Loan Amount (?),Loan Term (Months),Credit Score,Loan Status,total_assets_value
0,L001,0,0,No,"8,50,000","15,00,000",120,810,Approved,"25,00,00003,00,0006,00,000"
1,L002,2,0,Yes,"6,20,000","18,00,000",180,760,Approved,"18,00,0005,00,0002,00,0004,00,000"
2,L003,3,1,No,"2,80,000","12,00,000",240,590,Rejected,"8,00,000050,0001,20,000"
3,L004,1,0,No,"12,00,000","20,00,000",180,845,Approved,"40,00,00010,00,0008,00,00012,00,000"
4,L005,4,1,Yes,"3,50,000","15,00,000",240,610,Rejected,"10,00,0001,00,0001,00,0002,50,000"
5,L006,0,0,No,"15,00,000","25,00,000",120,890,Approved,"50,00,00020,00,00015,00,00020,00,000"
6,L007,2,0,No,"5,00,000","10,00,000",60,720,Approved,"16,00,00001,50,0003,00,000"
7,L008,5,1,Yes,"2,20,000","14,00,000",300,540,Rejected,"6,00,0000080,000"
8,L009,1,0,Yes,"9,00,000","16,00,000",120,790,Approved,"28,00,0008,00,0004,00,0007,00,000"
9,L010,3,1,No,"3,80,000","13,00,000",180,630,Rejected,"12,00,0002,00,0001,20,0002,20,000"

In [32]:
new['Self Employed']=le.fit_transform(new['Self Employed'])
new['Loan Status']=le.fit_transform(new['Loan Status'])

In [33]:
new

,Loan ID,No. of Dependencies,Education,Self Employed,Income/Annum (?),Loan Amount (?),Loan Term (Months),Credit Score,Loan Status,total_assets_value
0,L001,0,0,0,"8,50,000","15,00,000",120,810,0,"25,00,00003,00,0006,00,000"
1,L002,2,0,1,"6,20,000","18,00,000",180,760,0,"18,00,0005,00,0002,00,0004,00,000"
2,L003,3,1,0,"2,80,000","12,00,000",240,590,1,"8,00,000050,0001,20,000"
3,L004,1,0,0,"12,00,000","20,00,000",180,845,0,"40,00,00010,00,0008,00,00012,00,000"
4,L005,4,1,1,"3,50,000","15,00,000",240,610,1,"10,00,0001,00,0001,00,0002,50,000"
5,L006,0,0,0,"15,00,000","25,00,000",120,890,0,"50,00,00020,00,00015,00,00020,00,000"
6,L007,2,0,0,"5,00,000","10,00,000",60,720,0,"16,00,00001,50,0003,00,000"
7,L008,5,1,1,"2,20,000","14,00,000",300,540,1,"6,00,0000080,000"
8,L009,1,0,1,"9,00,000","16,00,000",120,790,0,"28,00,0008,00,0004,00,0007,00,000"
9,L010,3,1,0,"3,80,000","13,00,000",180,630,1,"12,00,0002,00,0001,20,0002,20,000"

In [34]:
new.isnull().values.any()

np.False_

In [35]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in C:\Users\Easwar\AppData\Roaming\Python\Python311\site-packages (2.2.6)
Note: you may need to restart the kernel to use updated packages.

In [36]:
import numpy as np

In [38]:
new['Income/Annum (?)'] = (
    new['Income/Annum (?)']
    .str.replace(',', '')
    .astype(float)
)

new['Income/Annum (?)'] = np.log(new['Income/Annum (?)'])

In [45]:
new['Loan Amount (?)'] = np.log(new['Loan Amount (?)'])

In [46]:
new['total_assets_value'] = (
    new['total_assets_value']
    .str.replace(',', '')
    .astype(float)
)

new['total_assets_value'] = np.log(new['total_assets_value'])

In [47]:
new

,Loan ID,No. of Dependencies,Education,Self Employed,Income/Annum (?),Loan Amount (?),Loan Term (Months),Credit Score,Loan Status,total_assets_value
0,L001,0,0,0,13.652992,2.654718,120,810,0,44.665408
1,L002,2,0,1,13.337475,2.667457,180,760,0,55.849829
2,L003,3,1,0,12.542545,2.638902,240,590,1,41.223388
3,L004,1,0,0,13.997832,2.674746,180,845,0,61.253507
4,L005,4,1,1,12.765688,2.654718,240,610,1,55.262042
5,L006,0,0,0,14.220976,2.690009,120,890,0,63.779235
6,L007,2,0,0,13.122363,2.625792,60,720,0,44.219120
7,L008,5,1,1,12.301383,2.649855,300,540,1,29.422781
8,L009,1,0,1,13.710150,2.659246,120,790,0,56.291662
9,L010,3,1,0,12.847927,2.644604,180,630,1,55.444364

In [48]:
X=new.drop(columns=['Loan Status','Loan ID'])

In [49]:
X

,No. of Dependencies,Education,Self Employed,Income/Annum (?),Loan Amount (?),Loan Term (Months),Credit Score,total_assets_value
0,0,0,0,13.652992,2.654718,120,810,44.665408
1,2,0,1,13.337475,2.667457,180,760,55.849829
2,3,1,0,12.542545,2.638902,240,590,41.223388
3,1,0,0,13.997832,2.674746,180,845,61.253507
4,4,1,1,12.765688,2.654718,240,610,55.262042
5,0,0,0,14.220976,2.690009,120,890,63.779235
6,2,0,0,13.122363,2.625792,60,720,44.219120
7,5,1,1,12.301383,2.649855,300,540,29.422781
8,1,0,1,13.710150,2.659246,120,790,56.291662
9,3,1,0,12.847927,2.644604,180,630,55.444364

In [50]:
Y=new['Loan Status']

In [51]:
Y

0    0
1    0
2    1
3    0
4    1
5    0
6    0
7    1
8    0
9    1
Name: Loan Status, dtype: int64

In [52]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.2, random_state=42)

In [53]:
x_train.shape

(8, 8)

In [54]:
x_test.shape

(2, 8)

In [55]:
from sklearn.linear_model import LogisticRegression
lg_model = LogisticRegression(max_iter=2000, penalty='l2')

In [56]:
model = lg_model.fit(x_train, y_train)

C:\Users\Easwar\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

In [57]:
model

LogisticRegression(max_iter=2000, penalty='l2')

In [58]:
y_pred = model.predict(x_test)

In [59]:
y_pred

array([0, 0])